### ISSUE TITLE
Surface errors from browserify

### ISSUE THREAD

**Issue by hlfcoding** [jhnstn/bundbi#1]
It appears we're not doing that and just exiting: https://github.com/jhnstn/bundbi/blob/6c0fbfd/lib/bundle.js#L80

**Comment by jhnstn** [comment]
@hlfcoding are you not seeing an expected message?
The line your reference is not exiting the process but calling a function called `exit`.
`exit` is defined here https://github.com/jhnstn/bundbi/blob/master/lib/exit.js

I can see the confusion however. Any suggestions on renaming the function? Maybe `exitWithMessage`?

**Comment by hlfcoding** [comment]
Yup, in our case, it was caused by requiring a module with the wrong name.
